import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner"; // 🔔 Sonner import qilindi

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "It School",
  description: "Generated by It-school group",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen bg-gray-100`}>
        <div>{children}</div>

        {/* 🔔 Sonner Toaster */}
        <Toaster
          position="top-right"
          richColors // rang-barang animatsiyali toastlar
          closeButton // yopish tugmasi
          toastOptions={{
            duration: 4000, // toastning davomiyligi 4 soniya
          }}
        />
      </body>
    </html>
  );
}
